AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MTA Encyclopedia Backend

Parameters:
  UserPoolId:
    Type: String
    Default: us-east-1_WgVikn28P

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        TABLE_NAME: user_profiles

Resources:

  # API Gateway, w/ Cognito Authorizer
  MtaeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,PUT,POST,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}'

  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/getProfile.handler
      Events:
        GetProfile:
          Type: Api
          Properties:
            RestApiId: !Ref MtaeApi
            Path: /profile/{userId}
            Method: GET
            Auth:
              Authorizer: NONE
      Policies:
        - DynamoDBReadPolicy:
            TableName: user_profiles
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/functions/getProfile.ts

  UpdateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/updateProfile.handler
      Events:
        UpdateProfile:
          Type: Api
          Properties:
            RestApiId: !Ref MtaeApi
            Path: /profile
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: user_profiles
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/functions/updateProfile.ts

  # Favorite Stops Lambda 
  GetFavoriteStopsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/getFavoriteStops.handler
      Events:
        GetFavorites:
          Type: Api
          Properties:
            RestApiId: !Ref MtaeApi
            Path: /profile/favorites
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: user_profiles
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/functions/getFavoriteStops.ts

  UpdateFavoriteStopsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/updateFavoriteStops.handler
      Events:
        UpdateFavorites:
          Type: Api
          Properties:
            RestApiId: !Ref MtaeApi
            Path: /profile/favorites
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: user_profiles
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/functions/updateFavoriteStops.ts

# Outputs:
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${MtaeApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
